@startuml
[*] -> 注文作成中: 初期状態
注文作成中 -> 注文確認待ち : Userが商品をカートに追加
注文確認待ち -> 支払い待ち: ユーザーが注文を確定する
支払い待ち -> 配送準備中: 支払い完了
配送準備中 -> 配送済み: 配送が完了
注文確認待ち --> キャンセル済み: ユーザーが注文をキャンセル
支払い待ち --> キャンセル済み: キャンセル済み
支払い待ち -> 支払い失敗: 支払いが失敗
支払い失敗 --> 支払い待ち: 再度支払い通知
@enduml